INSERT INTO target.goods_dimension
  (goods_id,
   goods_sn,
   goods_name,
   category_id,
   category_name,
   category_keywords,
   category_desc,
   category_pid,
   brand_id,
   gallery,
   keywords,
   brief,
   is_on_sale,
   sort_order,
   pic_url,
   share_url,
   is_new,
   is_hot,
   unit,
   counter_price,
   retail_price,
   detail,
   product_id,
   specifications,
   gp_add_date,
   gp_add_time,
   gp_update_date,
   gp_update_time,
   gp_deleted,
   category_icon_url,
   category_pic_url,
   category_level,
   category_sort_order,
   category_add_date,
   category_add_time,
   category_update_date,
   category_update_time,
   category_deleted,
   goods_add_date,
   goods_add_time,
   goods_update_date,
   goods_update_time,
   goods_deleted)
SELECT
   og.id AS goods_id,
   og.goods_sn,
   og.name AS goods_name,
   category_id,
   oc.name AS category_name,
   oc.keywords AS category_keywords,
   oc.cdesc AS category_desc,
   oc.pid AS category_pid,
   og.brand_id,
   og.gallery,
   og.keywords,
   og.brief,
   og.is_on_sale,
   og.sort_order,
   og.pic_url,
   og.share_url,
   og.is_new,
   og.is_hot,
   og.unit,
   og.counter_price,
   og.retail_price,
   og.detail,
   ogp.id AS product_id,
   ogp.specifications,
   to_char(ogp.add_time,'YYYYMMDD') :: INTEGER AS gp_add_date,
   0 AS gp_add_time,
   to_char(ogp.update_time, 'YYYYMMDD') :: INTEGER AS gp_update_date,
   0 AS gp_update_time,
   ogp.deleted,
   oc.icon_url AS category_icon_url,
   oc.pic_url AS category_pic_url,
   oc.level AS category_level,
   oc.sort_order AS category_sort_order,
   to_char(oc.add_time, 'YYYYMMDD') :: INTEGER AS category_add_date,
   0 AS category_add_time,
   to_char(oc.update_time, 'YYYYMMDD') :: INTEGER AS category_update_date,
   0 AS category_update_time,
   oc.deleted AS category_deleted,
   to_char(og.add_time, 'YYYYMMDD') :: INTEGER AS goods_add_date,
   0 AS goods_add_time,
   to_char(og.update_time, 'YYYYMMDD') :: INTEGER AS goods_update_date,
   0 AS goods_update_time,
   og.deleted AS goods_deleted 
FROM original.original_goods og,
   original.original_goods_product ogp,
   original.original_category oc 
WHERE og.category_id = oc.id AND og.id = ogp.goods_id
ORDER BY og.id, ogp.id;
