INSERT INTO target.user_dimension
  (user_id,
   username,
   password,
   gender,
   birthday,
   last_login_date,
   last_login_time,
   last_login_ip,
   user_level,
   nickname,
   mobile,
   avatar,
   weixin_openid,
   session_key,
   status,
   add_date,
   add_time,
   update_date,
   update_time,
   deleted)
SELECT id AS user_id,
       username,
       password,
       gender,
       to_char(birthday, 'YYYYMMDD') :: INTEGER AS birthday,
       to_char(last_login_time, 'YYYYMMDD') :: INTEGER AS last_login_date,
       0 AS last_login_time,
       last_login_ip,
       user_level,
       nickname,
       mobile,
       avatar,
       weixin_openid,
       session_key,
       status,
       to_char(add_time, 'YYYYMMDD') :: INTEGER AS add_date,
       0 AS add_time,
       to_char(update_time, 'YYYYMMDD') :: INTEGER AS update_date,
       0 AS update_time,
       deleted
  FROM original.original_user
ORDER BY id;
